language: android
#jdk:
#    - oraclejdk8
#sudo: false
#install: gradle wrapper --gradle-version 4.4

env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - extra-android-support
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

#before_script:
# - ./gradlew :app:assembleDebug
#- chmod a+x gradlew
#- chmod a+x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest lint --stacktrace
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

#upload code coverage to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)

