language: android
#jdk:
#    - oraclejdk8
#sudo: false
#install: gradle wrapper --gradle-version 4.4

env:
#  global:
#    MALLOC_ARENA_MAX=2
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a


android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-19
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - extra-android-support
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --skin WVGA800
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
# - ./gradlew :app:assembleDebug
#- chmod a+x gradlew
#- chmod a+x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew test connectedAndroidTest
  - ./gradlew build jacocoTestReport lint --stacktrace

#upload code coverage to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)

